### ISSUE TITLE
unhandled exceptions not logged

### ISSUE THREAD

**Issue by quape** [wolasss/meteor-sentry#1]
Hi and thanks for the package. I added it like written in the docs. Logger.info() works fine but when I produce an unhandled exception its not logged to the service. Anything missing?

**Comment by wolasss** [comment]
Hey, 

does it happen on the client or on the server?

**Comment by quape** [comment]
On the server. I only added the init code on the server.

**Comment by wolasss** [comment]
Do you have any `process.on('uncaughtException', callback)` in your server code?

**Comment by quape** [comment]
No, nowhere... Ok I figured out, when I produce an uncaught exception right in `Meteor.startup()` it will be logged. If I do it somewhere else, e.g. in `Meteor.methods()`, nothing happens.
I used an empty Meteor project for testing by the way.

**Comment by wolasss** [comment]
Ok, I'll take a look at this asap

**Comment by wolasss** [comment]
@quape Well, the reason why the errors are not caught in the methods is that the exceptions thrown in the methods are handled by the meteor and returned as the err parameter in the method callback (so these exceptions are caught, but by the meteor). I think the best way to handle this is to log them manually in the method callback

**Comment by quape** [comment]
Perfect, so I'll do it like this, thanks!
